### ISSUE TITLE
Why did you choose the same name as my elm-collision library?

### ISSUE THREAD

**Issue by bakkemo** [burabure/elm-collision#1]

**Comment by burabure** [comment]
didn't know there was another. Thankfully elm packages are namespaced =)

Maybe it would be a good idea to consider merging the libraries?

**Comment by burabure** [comment]
I don't see an overlap in functionality so it would be an easy merge. My functions right now are efficient for rectangles and circles while yours is efficient for convex polygons

**Comment by bakkemo** [comment]
I don't see the point. There is overlap in that my library handles both
circles and rectangles just fine. GJK handles any "convex" shape (the
quotes because the shape doesn't need to live in Euclidean space), not just
polygons. It's not like I am unaware of the special case radius and corner
calculations for circles and squares, its that special case stuff doesn't
buy you much. With simplex caching and tail call optimization for ES6, GJK
would most often reduce to two dot products and a comparison, making GJK on
par with (or better than) special case stuff. I notice you also are not
even handling intersection between a circle and a rectangle.

**Comment by burabure** [comment]
You might be right. but I think I have a different take on it in general.

I'm implementing AST for the next release which will handle collisions for convex geometry. I don't see any libraries implementing it, so that should be interesting.

**Comment by bakkemo** [comment]
I have an idea what you might mean by AST for collisions, but I'm afraid
I'm not quite sure. Could you give me a handwavy example?

**Comment by burabure** [comment]
whoops, not AST but SAT

http://www.metanetsoftware.com/technique/tutorialA.html

**Comment by bakkemo** [comment]
Ah. That was in fact my suggestion. I am very interested in the result.
