### ISSUE TITLE
Port to Elm 0.18

### ISSUE THREAD

**Issue by passiomatic** [burabure/elm-collision#2]
Do you have plans to port the library to latest Elm version? Is it just a matter to update elm-package information or some additional work is required? Thank you for your time.

**Comment by burabure** [comment]
I don't think I'll keep supporting this directly because I no longer have time to invest in elm, but I'm open to pull requests

**Comment by passiomatic** [comment]
Great, I'll have a look in the upcoming weeks.

**Comment by passiomatic** [comment]
Added a PR: https://github.com/burabure/elm-collision/pull/3

**Comment by passiomatic** [comment]
Case closed 😁
